version: "3"
networks:
  kong-net:
    driver: bridge
services:
  kong-database:
    image: postgres:9.6.18-alpine
    container_name: kong-database
    restart: always
    networks:
      - kong-net
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - /db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 5s
      timeout: 5s
      retries: 5
  kong-migration:
    image: kong:2.0.4-alpine
    command: "kong migrations bootstrap"
    networks:
      - kong-net
    restart: on-failure
    environment:
      KONG_PG_HOST: kong-database
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: 123456
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
    links:
      - kong-database
    depends_on:
      - kong-database
  kong:
    image: kong:2.0.4-alpine
    restart: always
    container_name: kong
    networks:
      - kong-net
    environment:
      KONG_PG_HOST: kong-database
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PROXY_LISTEN_SSL: 0.0.0.0:8443
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_DATABASE: postgres
      KONG_PG_PASSWORD: 123456
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_PG_HOST: kong-database
    depends_on:
      - kong-migration
      - kong-database
    healthcheck:
      test: ["CMD", "curl", "-f", "http://kong:8001"]
      interval: 5s
      timeout: 2s
      retries: 15
    ports:
      - "8001:8001"
      - "8000:8000"
      - "8443:8443"
      - "8444:8444"
  konga-prepare:
    image: pantsel/konga:0.14.9
    command: "-c prepare -a postgres -u postgresql://kong:123456@kong-database:5432/konga"
    networks:
      - kong-net
    restart: on-failure
    links:
      - kong-database
    depends_on:
      - kong-database
  konga:
    image: pantsel/konga:0.14.9
    restart: always
    container_name: konga
    networks:
        - kong-net
    environment:
      NODE_ENV: production
      DB_ADAPTER: postgres
      DB_URI: postgresql://kong:123456@kong-database:5432/konga
    depends_on:
      - kong-database
    ports:
      - "1337:1337"