version: '3'
services:
  myweb:
    restart: always
    image: go_docker:1.0
    container_name: godocker
    volumes:
      - /root/compose/config.yaml:/compose/config.yaml
    ports:
      - 6001:6001
  mysql:
    restart: always
    image: mysql:5.7
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    command:
      --max_allowed_packet=128M
    volumes:
      - /root/mysql/logs:/var/log/mysql
      - /root/mysql/data:/var/lib/mysql